const dataList = [
  {
    "className": "A股",
    "classCode": "CHINA_STOCK",
    "unit": 83,
    "profitRate": null,
    "accProfitRate": 0.316,
    "percent": 0.524,
    "isCash": false,
    "compList": [
      {
        "fund": {
          "fundCode": "100032",
          "fundName": "富国中证红利指数增强A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.9730",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "中证红利",
        "nav": 0.973,
        "navDate": 1687881600000,
        "dailyReturn": 0.0062,
        "planUnit": 14,
        "strategyType": "LONG",
        "unitValue": 0.6698,
        "percent": 0.0882,
        "isCash": false,
        "accProfit": 0.4242
      },
      {
        "fund": {
          "fundCode": "000478",
          "fundName": "建信中证500指数增强A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "2.6709",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "建信500",
        "nav": 2.6709,
        "navDate": 1687795200000,
        "dailyReturn": 0.0119,
        "planUnit": 10,
        "strategyType": "LONG",
        "unitValue": 2.3545,
        "percent": 0.0602,
        "isCash": false,
        "accProfit": 0.1867
      },
      {
        "fund": {
          "fundCode": "001052",
          "fundName": "华夏中证500ETF联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.6958",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "中证500",
        "nav": 0.6958,
        "navDate": 1687795200000,
        "dailyReturn": 0.0097,
        "planUnit": 8,
        "strategyType": "LONG",
        "unitValue": 0.5892,
        "percent": 0.0501,
        "isCash": false,
        "accProfit": 0.2147
      },
      {
        "fund": {
          "fundCode": "100038",
          "fundName": "富国沪深300指数增强A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.4920",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "富国300",
        "nav": 1.492,
        "navDate": 1687881600000,
        "dailyReturn": 0.0007,
        "planUnit": 7,
        "strategyType": "LONG",
        "unitValue": 1.1713,
        "percent": 0.0476,
        "isCash": false,
        "accProfit": 0.2738
      },
      {
        "fund": {
          "fundCode": "001180",
          "fundName": "广发医药卫生联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.8986",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "全指医药",
        "nav": 0.8986,
        "navDate": 1687795200000,
        "dailyReturn": 0.0046,
        "planUnit": 7,
        "strategyType": "LONG",
        "unitValue": 0.8433,
        "percent": 0.0432,
        "isCash": false,
        "accProfit": 0.2796
      },
      {
        "fund": {
          "fundCode": "000968",
          "fundName": "广发养老指数A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.9182",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "投顾策略单只基金所有客户持有份额总和，不得超过该基金总份额20%，指数基金不得超过30%。该品种即将达到该限制，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "养老产业",
        "nav": 0.9182,
        "navDate": 1687881600000,
        "dailyReturn": -0.0033,
        "planUnit": 7,
        "strategyType": "LONG",
        "unitValue": 0.9923,
        "percent": 0.0351,
        "isCash": false,
        "accProfit": 0.1232
      },
      {
        "fund": {
          "fundCode": "001469",
          "fundName": "广发中证全指金融地产联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.9469",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "全指金融",
        "nav": 0.9469,
        "navDate": 1687795200000,
        "dailyReturn": 0.0122,
        "planUnit": 5,
        "strategyType": "LONG",
        "unitValue": 0.9897,
        "percent": 0.0271,
        "isCash": false,
        "accProfit": -0.0432
      },
      {
        "fund": {
          "fundCode": "002708",
          "fundName": "大摩健康产业混合A",
          "fundInvestType": "3",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.9820",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "大摩健康产业",
        "nav": 1.982,
        "navDate": 1687881600000,
        "dailyReturn": -0.0025,
        "planUnit": 4,
        "strategyType": "LONG",
        "unitValue": 2.3649,
        "percent": 0.0255,
        "isCash": false,
        "accProfit": -0.1598
      },
      {
        "fund": {
          "fundCode": "161017",
          "fundName": "富国中证500指数增强A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "2.2370",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "富国500",
        "nav": 2.237,
        "navDate": 1687881600000,
        "dailyReturn": -0.0022,
        "planUnit": 3,
        "strategyType": "LONG",
        "unitValue": 1.4561,
        "percent": 0.0246,
        "isCash": false,
        "accProfit": 0.5363
      },
      {
        "fund": {
          "fundCode": "001051",
          "fundName": "华夏上证50ETF联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.8684",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "上证50",
        "nav": 0.8684,
        "navDate": 1687795200000,
        "dailyReturn": 0.0068,
        "planUnit": 4,
        "strategyType": "LONG",
        "unitValue": 0.7665,
        "percent": 0.023,
        "isCash": false,
        "accProfit": 0.4915
      },
      {
        "fund": {
          "fundCode": "502010",
          "fundName": "易方达中证全指证券公司指数(LOF)A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.0058",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "证券公司",
        "nav": 1.0058,
        "navDate": 1687795200000,
        "dailyReturn": 0.0087,
        "planUnit": 3,
        "strategyType": "LONG",
        "unitValue": 0.9093,
        "percent": 0.019,
        "isCash": false,
        "accProfit": 0.2378
      },
      {
        "fund": {
          "fundCode": "000942",
          "fundName": "广发信息技术联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.1143",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "信息技术",
        "nav": 1.1143,
        "navDate": 1687795200000,
        "dailyReturn": 0.0028,
        "planUnit": 2,
        "strategyType": "LONG",
        "unitValue": 1.074,
        "percent": 0.0166,
        "isCash": false,
        "accProfit": 0.1338
      },
      {
        "fund": {
          "fundCode": "012323",
          "fundName": "华宝医疗ETF联接C",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.7249",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "该品种属于短期波段交易，买卖频率较高，如果不能及时跟车买入、卖出，可能会由于持仓不足7天而缴纳惩罚性赎回费，为了避免产生这类损失，不支持自主买入。"
        },
        "shareType": "A",
        "variety": "华宝医疗C",
        "nav": 0.7249,
        "navDate": 1687795200000,
        "dailyReturn": 0.0057,
        "planUnit": 2,
        "strategyType": "GRID",
        "unitValue": 0.7611,
        "percent": 0.0147,
        "isCash": false,
        "accProfit": -0.0476
      },
      {
        "fund": {
          "fundCode": "000051",
          "fundName": "华夏沪深300ETF联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.3665",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "沪深300",
        "nav": 1.3665,
        "navDate": 1687795200000,
        "dailyReturn": 0.0093,
        "planUnit": 2,
        "strategyType": "LONG",
        "unitValue": 1.3102,
        "percent": 0.0142,
        "isCash": false,
        "accProfit": 0.435
      },
      {
        "fund": {
          "fundCode": "004752",
          "fundName": "广发中证传媒ETF联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.8939",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "中证传媒",
        "nav": 0.8939,
        "navDate": 1687881600000,
        "dailyReturn": -0.0137,
        "planUnit": 2,
        "strategyType": "LONG",
        "unitValue": 0.9971,
        "percent": 0.0128,
        "isCash": false,
        "accProfit": 0.0675
      },
      {
        "fund": {
          "fundCode": "011309",
          "fundName": "富国消费主题混合C",
          "fundInvestType": "3",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "2.5330",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "该品种属于短期波段交易，买卖频率较高，如果不能及时跟车买入、卖出，可能会由于持仓不足7天而缴纳惩罚性赎回费，为了避免产生这类损失，不支持自主买入。"
        },
        "shareType": "A",
        "variety": "富国消费C",
        "nav": 2.533,
        "navDate": 1687881600000,
        "dailyReturn": 0.0004,
        "planUnit": 1,
        "strategyType": "GRID",
        "unitValue": 2.534,
        "percent": 0.0078,
        "isCash": false,
        "accProfit": -0.0004
      },
      {
        "fund": {
          "fundCode": "162412",
          "fundName": "华宝医疗ETF联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.7278",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "华宝医疗A",
        "nav": 0.7278,
        "navDate": 1687795200000,
        "dailyReturn": 0.0057,
        "planUnit": 1,
        "strategyType": "LONG",
        "unitValue": 0.78,
        "percent": 0.0073,
        "isCash": false,
        "accProfit": -0.067
      },
      {
        "fund": {
          "fundCode": "519915",
          "fundName": "富国消费主题混合A",
          "fundInvestType": "3",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "2.5700",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "富国消费",
        "nav": 2.57,
        "navDate": 1687881600000,
        "dailyReturn": 0.0004,
        "planUnit": 1,
        "strategyType": "LONG",
        "unitValue": 2.8312,
        "percent": 0.007,
        "isCash": false,
        "accProfit": -0.013
      },
      {
        "fund": {
          "fundCode": "001064",
          "fundName": "广发中证环保ETF联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.9006",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "中证环保",
        "nav": 0.9006,
        "navDate": 1687881600000,
        "dailyReturn": 0.0096,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.5831
      },
      {
        "fund": {
          "fundCode": "110026",
          "fundName": "易方达创业板ETF联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "2.2404",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "易方达创业板",
        "nav": 2.2404,
        "navDate": 1687795200000,
        "dailyReturn": 0.0026,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.2264
      },
      {
        "fund": {
          "fundCode": "003765",
          "fundName": "广发创业板ETF联接A",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.1849",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "广发创业板",
        "nav": 1.1849,
        "navDate": 1687881600000,
        "dailyReturn": -0.0041,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.3136
      },
      {
        "fund": {
          "fundCode": "002903",
          "fundName": "广发中证500ETF联接C",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.0894",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "该品种属于短期波段交易，买卖频率较高，如果不能及时跟车买入、卖出，可能会由于持仓不足7天而缴纳惩罚性赎回费，为了避免产生这类损失，不支持自主买入。"
        },
        "shareType": "A",
        "variety": "中证500C类",
        "nav": 1.0894,
        "navDate": 1687795200000,
        "dailyReturn": 0.0098,
        "planUnit": 0,
        "strategyType": "GRID",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.5293
      },
      {
        "fund": {
          "fundCode": "001513",
          "fundName": "易方达信息产业混合",
          "fundInvestType": "3",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "2.5930",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "易方达信息产业",
        "nav": 2.593,
        "navDate": 1687881600000,
        "dailyReturn": -0.0133,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.2802
      },
      {
        "fund": {
          "fundCode": "110022",
          "fundName": "易方达消费行业",
          "fundInvestType": "1",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "3.7830",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "易方达消费行业",
        "nav": 3.783,
        "navDate": 1687881600000,
        "dailyReturn": 0.0021,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.6059
      },
      {
        "fund": {
          "fundCode": "000727",
          "fundName": "融通健康产业灵活配置混合A",
          "fundInvestType": "3",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "3.0170",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": "10000000.00",
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "融通健康产业",
        "nav": 3.017,
        "navDate": 1687881600000,
        "dailyReturn": -0.003,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.3024
      }
    ]
  },
  {
    "className": "现金",
    "classCode": "CASH",
    "unit": 29,
    "profitRate": null,
    "accProfitRate": null,
    "percent": 0.2256,
    "isCash": true,
    "compList": [
      {
        "variety": "现金",
        "planUnit": 29,
        "isCash": true,
        "accProfit": 0.267,
        "percent": 0.2256
      }
    ]
  },
  {
    "className": "海外新兴市场股票",
    "classCode": "OVERSEA_STOCK_EMERGING",
    "unit": 25,
    "profitRate": null,
    "accProfitRate": 0.0351,
    "percent": 0.1446,
    "isCash": false,
    "compList": [
      {
        "fund": {
          "fundCode": "000071",
          "fundName": "华夏恒生ETF联接A",
          "fundInvestType": "1",
          "isQdii": true,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.1450",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "恒生指数",
        "nav": 1.145,
        "navDate": 1687795200000,
        "dailyReturn": 0.0179,
        "planUnit": 14,
        "strategyType": "LONG",
        "unitValue": 1.1328,
        "percent": 0.0814,
        "isCash": false,
        "accProfit": 0.127
      },
      {
        "fund": {
          "fundCode": "012348",
          "fundName": "天弘恒生科技指数(QDII)A",
          "fundInvestType": "1",
          "isQdii": true,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.5919",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "恒生科技",
        "nav": 0.5919,
        "navDate": 1687881600000,
        "dailyReturn": 0.0063,
        "planUnit": 5,
        "strategyType": "LONG",
        "unitValue": 0.6599,
        "percent": 0.0341,
        "isCash": false,
        "accProfit": -0.1031
      },
      {
        "fund": {
          "fundCode": "164906",
          "fundName": "交银施罗德中证海外中国互联网指数(QDII-LOF)A",
          "fundInvestType": "1",
          "isQdii": true,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.9479",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "中国海外互联",
        "nav": 0.9479,
        "navDate": 1687795200000,
        "dailyReturn": 0.0264,
        "planUnit": 4,
        "strategyType": "LONG",
        "unitValue": 1.5822,
        "percent": 0.0172,
        "isCash": false,
        "accProfit": -0.0546
      },
      {
        "fund": {
          "fundCode": "014424",
          "fundName": "博时恒生医疗保健ETF发起式联接(QDII)A",
          "fundInvestType": "1",
          "isQdii": true,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.7690",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "恒生医疗",
        "nav": 0.769,
        "navDate": 1687881600000,
        "dailyReturn": -0.009,
        "planUnit": 1,
        "strategyType": "LONG",
        "unitValue": 0.9209,
        "percent": 0.0067,
        "isCash": false,
        "accProfit": 0.1156
      },
      {
        "fund": {
          "fundCode": "006327",
          "fundName": "易方达中证海外联接人民币A",
          "fundInvestType": "1",
          "isQdii": true,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.7866",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": "5000.00",
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "易方达中概互联",
        "nav": 0.7866,
        "navDate": 1687795200000,
        "dailyReturn": 0.0249,
        "planUnit": 1,
        "strategyType": "LONG",
        "unitValue": 1.0963,
        "percent": 0.0052,
        "isCash": false,
        "accProfit": -0.2825
      }
    ]
  },
  {
    "className": "境内债券",
    "classCode": "CHINA_BOND",
    "unit": 8,
    "profitRate": null,
    "accProfitRate": 0.3189,
    "percent": 0.0591,
    "isCash": false,
    "compList": [
      {
        "fund": {
          "fundCode": "340001",
          "fundName": "兴全可转债混合",
          "fundInvestType": "3",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.0561",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "兴全转债",
        "nav": 1.0561,
        "navDate": 1687881600000,
        "dailyReturn": -0.002,
        "planUnit": 4,
        "strategyType": "LONG",
        "unitValue": 0.7257,
        "percent": 0.0312,
        "isCash": false,
        "accProfit": 0.4964
      },
      {
        "fund": {
          "fundCode": "110027",
          "fundName": "易方达安心债券A",
          "fundInvestType": "2",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.8669",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "易方达安心回报债",
        "nav": 1.8669,
        "navDate": 1687881600000,
        "dailyReturn": 0.0005,
        "planUnit": 3,
        "strategyType": "LONG",
        "unitValue": 1.4859,
        "percent": 0.0197,
        "isCash": false,
        "accProfit": 0.2823
      },
      {
        "fund": {
          "fundCode": "003376",
          "fundName": "广发中债7-10年国开债指数A",
          "fundInvestType": "2",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.2828",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "7-10国开债",
        "nav": 1.2828,
        "navDate": 1687881600000,
        "dailyReturn": 0.0003,
        "planUnit": 1,
        "strategyType": "LONG",
        "unitValue": 1.2455,
        "percent": 0.0082,
        "isCash": false,
        "accProfit": 0.1164
      },
      {
        "fund": {
          "fundCode": "050027",
          "fundName": "博时信用债纯债债券A",
          "fundInvestType": "2",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.1257",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "博时信用债",
        "nav": 1.1257,
        "navDate": 1687881600000,
        "dailyReturn": 0.0002,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.086
      },
      {
        "fund": {
          "fundCode": "270048",
          "fundName": "广发纯债债券A",
          "fundInvestType": "2",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.2331",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": "10000000.00",
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "广发纯债",
        "nav": 1.2331,
        "navDate": 1687881600000,
        "dailyReturn": 0,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.1364
      },
      {
        "fund": {
          "fundCode": "519977",
          "fundName": "长信可转债债券A",
          "fundInvestType": "2",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.6624",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "长信可转债",
        "nav": 1.6624,
        "navDate": 1687881600000,
        "dailyReturn": -0.0025,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.19
      },
      {
        "fund": {
          "fundCode": "000563",
          "fundName": "南方通利A",
          "fundInvestType": "2",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.1005",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "南方通利纯债",
        "nav": 1.1005,
        "navDate": 1687881600000,
        "dailyReturn": 0,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.0527
      },
      {
        "fund": {
          "fundCode": "000147",
          "fundName": "易方达高等级信用债A",
          "fundInvestType": "2",
          "isQdii": false,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.1132",
          "navDate": "2023-06-28",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "易方达高等级信用债",
        "nav": 1.1132,
        "navDate": 1687881600000,
        "dailyReturn": 0.0002,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.0365
      }
    ]
  },
  {
    "className": "海外成熟市场股票",
    "classCode": "OVERSEA_STOCK_MATURE",
    "unit": 4,
    "profitRate": null,
    "accProfitRate": 0.4301,
    "percent": 0.0387,
    "isCash": false,
    "compList": [
      {
        "fund": {
          "fundCode": "270042",
          "fundName": "广发纳指100ETF联接人民币(QDII)A",
          "fundInvestType": "1",
          "isQdii": true,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "4.6209",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": "50000.00",
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "纳指100",
        "nav": 4.6209,
        "navDate": 1687795200000,
        "dailyReturn": 0.0178,
        "planUnit": 2,
        "strategyType": "LONG",
        "unitValue": 3.4171,
        "percent": 0.0209,
        "isCash": false,
        "accProfit": 0.3286
      },
      {
        "fund": {
          "fundCode": "050025",
          "fundName": "博时标普500ETF联接A",
          "fundInvestType": "1",
          "isQdii": true,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "3.5015",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "标普500",
        "nav": 3.5015,
        "navDate": 1687795200000,
        "dailyReturn": 0.0114,
        "planUnit": 2,
        "strategyType": "LONG",
        "unitValue": 2.9704,
        "percent": 0.0178,
        "isCash": false,
        "accProfit": 0.2893
      },
      {
        "fund": {
          "fundCode": "000614",
          "fundName": "华安德国(DAX)ETF联接A",
          "fundInvestType": "1",
          "isQdii": true,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.3740",
          "navDate": "2023-06-26",
          "personalHighestBuyAmount": "500000.00",
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "德国DAX",
        "nav": 1.374,
        "navDate": 1687708800000,
        "dailyReturn": -0.0101,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.2769
      },
      {
        "fund": {
          "fundCode": "001092",
          "fundName": "广发生物科技指数(QDII)A",
          "fundInvestType": "1",
          "isQdii": true,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.1090",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": "1000.00",
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "纳斯达克生物科技",
        "nav": 1.109,
        "navDate": 1687795200000,
        "dailyReturn": -0.0098,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.1142
      }
    ]
  },
  {
    "className": "黄金",
    "classCode": "GOLD",
    "unit": 1,
    "profitRate": null,
    "accProfitRate": 0.3495,
    "percent": 0.008,
    "isCash": false,
    "compList": [
      {
        "fund": {
          "fundCode": "000216",
          "fundName": "华安黄金易ETF联接A",
          "fundInvestType": "8",
          "isQdii": false,
          "canBuy": true,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.6090",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": null
        },
        "shareType": "A",
        "variety": "黄金",
        "nav": 1.609,
        "navDate": 1687795200000,
        "dailyReturn": 0,
        "planUnit": 1,
        "strategyType": "LONG",
        "unitValue": 1.1303,
        "percent": 0.008,
        "isCash": false,
        "accProfit": 0.3495
      }
    ]
  },
  {
    "className": "原油",
    "classCode": "OIL",
    "unit": 0,
    "profitRate": null,
    "accProfitRate": 0.2591,
    "percent": 0,
    "isCash": false,
    "compList": [
      {
        "fund": {
          "fundCode": "160416",
          "fundName": "华安标普石油指数A",
          "fundInvestType": "8",
          "isQdii": true,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.4860",
          "navDate": "2023-06-26",
          "personalHighestBuyAmount": "500000.00",
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "石油基金",
        "nav": 1.486,
        "navDate": 1687708800000,
        "dailyReturn": -0.0073,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.2789
      },
      {
        "fund": {
          "fundCode": "162411",
          "fundName": "华宝标普石油指数A",
          "fundInvestType": "8",
          "isQdii": true,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "0.6933",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": null,
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "华宝油气",
        "nav": 0.6933,
        "navDate": 1687795200000,
        "dailyReturn": 0.0054,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.2681
      },
      {
        "fund": {
          "fundCode": "501018",
          "fundName": "南方原油A",
          "fundInvestType": "8",
          "isQdii": true,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.0976",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": "5000000.00",
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "南方原油",
        "nav": 1.0976,
        "navDate": 1687795200000,
        "dailyReturn": -0.0027,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.2126
      }
    ]
  },
  {
    "className": "海外债券",
    "classCode": "OVERSEA_BOND",
    "unit": 0,
    "profitRate": null,
    "accProfitRate": 0.0519,
    "percent": 0,
    "isCash": false,
    "compList": [
      {
        "fund": {
          "fundCode": "001061",
          "fundName": "华夏海外收益债券A",
          "fundInvestType": "2",
          "isQdii": true,
          "canBuy": false,
          "canRedeem": true,
          "onSale": true,
          "nav": "1.3470",
          "navDate": "2023-06-27",
          "personalHighestBuyAmount": "5000.00",
          "cannotBuyReason": "主理人已清仓该品种，该品种价格暂时不符合长赢计划买入条件，自主买入具有很大的收益不确定性，因此暂时不支持自主买入。"
        },
        "shareType": "A",
        "variety": "海外收益债",
        "nav": 1.347,
        "navDate": 1687795200000,
        "dailyReturn": 0.0037,
        "planUnit": 0,
        "strategyType": "LONG",
        "unitValue": null,
        "percent": 0,
        "isCash": false,
        "accProfit": 0.0519
      }
    ]
  }
]
module.exports = dataList
